name: 'Setup Build Environment'
description: 'Setup common build environment for OBS Stabilizer'
inputs:
  platform:
    description: 'Platform type (ubuntu, windows, macos)'
    required: true
    default: 'ubuntu'
runs:
  using: 'composite'
  steps:

    - name: Cache Ubuntu packages
      if: inputs.platform == 'ubuntu'
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/apt/archives
          /var/lib/apt/lists
        key: ubuntu-packages-${{ runner.os }}-${{ hashFiles('.github/actions/setup-build-env/action.yml') }}
        restore-keys: |
          ubuntu-packages-${{ runner.os }}-

    - name: Install Ubuntu dependencies
      if: inputs.platform == 'ubuntu'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          build-essential \
          libopencv-dev \
          libgtest-dev \
          nlohmann-json3-dev \
          pkg-config \
          qtbase5-dev \
          qtbase5-dev-tools \
          cppcheck

    - name: Cache Homebrew packages
      if: inputs.platform == 'macos'
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/Homebrew
          /opt/homebrew/var/homebrew/locks
        key: homebrew-${{ runner.os }}-${{ hashFiles('.github/actions/setup-build-env/action.yml') }}
        restore-keys: |
          homebrew-${{ runner.os }}-

    - name: Install macOS dependencies
      if: inputs.platform == 'macos'
      shell: bash
      run: |
        brew upgrade cmake ninja opencv pkg-config googletest nlohmann-json

    - name: Setup MSVC (Windows)
      if: inputs.platform == 'windows'
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce

    - name: Cache vcpkg packages
      if: inputs.platform == 'windows'
      uses: actions/cache@v4
      with:
        path: |
          C:\vcpkg\installed
          C:\vcpkg\buildtrees
          C:\vcpkg\downloads
        key: vcpkg-${{ runner.os }}-${{ hashFiles('.github/actions/setup-build-env/action.yml') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Set VCPKG_ROOT environment variable
      if: inputs.platform == 'windows'
      shell: powershell
      run: |
        echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
        New-Item -ItemType Directory -Force -Path "C:\vcpkg\archives" | Out-Null
        echo "VCPKG_DEFAULT_BINARY_CACHE=C:\vcpkg\archives" >> $env:GITHUB_ENV

    - name: Install vcpkg and OpenCV (Windows)
      if: inputs.platform == 'windows'
      shell: powershell
      run: |
        if (Test-Path "C:\vcpkg\installed\x64-windows\include\opencv4") {
          Write-Host "OpenCV vcpkg cache found, skipping installation"
        } else {
          Write-Host "Installing vcpkg..."
          if (-not (Test-Path "C:\vcpkg")) {
            git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
            cd C:\vcpkg
            .\bootstrap-vcpkg.bat -disableMetrics
            .\vcpkg integrate install
          } else {
            cd C:\vcpkg
            if (-not (Test-Path ".\vcpkg.exe")) {
              .\bootstrap-vcpkg.bat -disableMetrics
            }
          }
          
          Write-Host "Installing OpenCV, GTest, and nlohmann-json via vcpkg (this may take a while)..."
          .\vcpkg install opencv:x64-windows gtest:x64-windows nlohmann-json:x64-windows
          Write-Host "OpenCV, GTest, and nlohmann-json installed successfully"
        }
