name: 'Setup Build Environment'
description: 'Setup common build environment for OBS Stabilizer'
inputs:
  platform:
    description: 'Platform type (ubuntu, windows, macos)'
    required: true
    default: 'ubuntu'
runs:
  using: 'composite'
  steps:
    - name: Validate platform input
      shell: bash
      run: |
        if [[ "${{ inputs.platform }}" != "ubuntu" && "${{ inputs.platform }}" != "windows" && "${{ inputs.platform }}" != "macos" ]]; then
          echo "Error: Invalid platform '${{ inputs.platform }}'. Must be one of: ubuntu, windows, macos"
          exit 1
        fi
    - name: Cache Ubuntu packages
      if: inputs.platform == 'ubuntu'
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/apt/archives
          /var/lib/apt/lists
        key: ubuntu-packages-${{ runner.os }}-${{ hashFiles('.github/actions/setup-build-env/action.yml') }}
        restore-keys: |
          ubuntu-packages-${{ runner.os }}-

    - name: Install Ubuntu dependencies
      if: inputs.platform == 'ubuntu'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          build-essential \
          libopencv-dev \
          pkg-config \
          qtbase5-dev \
          qtbase5-dev-tools

    - name: Cache Homebrew packages
      if: inputs.platform == 'macos'
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/Homebrew
          /opt/homebrew/var/homebrew/locks
        key: homebrew-${{ runner.os }}-${{ hashFiles('.github/actions/setup-build-env/action.yml') }}
        restore-keys: |
          homebrew-${{ runner.os }}-

    - name: Install macOS dependencies
      if: inputs.platform == 'macos'
      shell: bash
      run: |
        brew install cmake ninja opencv pkg-config

    - name: Setup MSVC (Windows)
      if: inputs.platform == 'windows'
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce

    - name: Cache vcpkg packages
      if: inputs.platform == 'windows'
      uses: actions/cache@v4
      with:
        path: |
          C:\vcpkg\installed
          C:\vcpkg\buildtrees
        key: vcpkg-${{ runner.os }}-${{ hashFiles('.github/actions/setup-build-env/action.yml') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Set VCPKG_ROOT environment variable
      if: inputs.platform == 'windows'
      shell: powershell
      run: |
        echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV

    - name: Install OpenCV (Windows)
      if: inputs.platform == 'windows'
      shell: powershell
      run: |
        vcpkg install opencv:x64-windows
