name: 'Configure CMake'
description: 'Configure CMake build for OBS Stabilizer'
inputs:
  platform:
    description: 'Platform type (ubuntu, windows, macos)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure CMake (Unix)
      if: inputs.platform != 'windows'
      shell: bash
      run: |
        mkdir -p build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
        echo "CMake configuration completed for standalone build"

    - name: Configure CMake (Windows)
      if: inputs.platform == 'windows'
      shell: powershell
      run: |
        mkdir build
        cd build
        $vcpkgRoot = "$env:VCPKG_ROOT"
        $toolchainFile = "$vcpkgRoot\scripts\buildsystems\vcpkg.cmake"
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE="$toolchainFile" -DVCPKG_TARGET_TRIPLET=x64-windows
        Write-Host "CMake configuration completed for standalone build"